name: Release

permissions:
  contents: write
  packages: write

on:
  release:
    types: [released]

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust compilation prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            protobuf-compiler
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src

      - name: Build the template
        run: cargo build --locked --release
        timeout-minutes: 90

      - name: Upload the binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/v8r
            target/release/wbuild/v8r-runtime/v8r_runtime.compact.compressed.wasm
